#!/usr/bin/env node

const fs = require('fs') // file system
const chalk = require('chalk')
const { exit } = require('process')
const file = process.argv[2]
// console.log(process.argv)

fs.readFile(file, { encoding: 'utf-8' }, (err, text) => {
  err
    ? console.error(chalk.red(err))
    : console.log(chalk.green(text.split('\n').length))
})

// \ alt + shift + 7
// \n = new line

// .rows.length;
